AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-lambda-example

  Sample SAM Template for go-lambda-example

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
    Metadata:
      DockerTag: go-lambda-example-v1
      DockerContext: .
      Dockerfile: Dockerfile
